server:
  port: 10010

spring:
  datasource:
    url: jdbc:mysql://139.186.75.113:3306/sbs?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  application:
    name: sbs-feign-server

  redis:
    host: 139.186.75.113
    port: 6379
    database: 0
    timeout: 500

  rabbitmq:
    host: 139.186.75.113
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/



netty:
  server:
    port: 12300
    host: 172.37.0.122

#可添加es集群,用","隔开
elasticsearch:
  address: localhost:9200

