
server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://139.186.75.113:3306/sbs?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  application:
    name: gateway-server

  redis:
    host: 139.186.75.113
    port: 6379
    database: 0
    timeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

zuul:
  routes:
    hello:
      path: /api/**
      url: http://127.0.0.1:10010/api
