server:
  port: 9011

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sbs?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  application:
    name: urule-client-server

urule:
  resporityServerUrl: http://localhost:9010
  knowledgeUpdateCycle: 1
